// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARKu9hmeFcvVoHFYYsCdVOjwLpNEUAoh0',
    appId: '1:407758740099:web:3067253382f37cad0319b6',
    messagingSenderId: '407758740099',
    projectId: 'focusbuddy-6a5cf',
    authDomain: 'focusbuddy-6a5cf.firebaseapp.com',
    storageBucket: 'focusbuddy-6a5cf.firebasestorage.app',
    measurementId: 'G-SWF3LQVXL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBeO35Oqk6qIODeGSDQRdtPoeNp30h73g',
    appId: '1:407758740099:android:957ab38eb9ca20bb0319b6',
    messagingSenderId: '407758740099',
    projectId: 'focusbuddy-6a5cf',
    storageBucket: 'focusbuddy-6a5cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALJ2K-lTiPxDtqYwHvBJAoKHLIeG6oPvk',
    appId: '1:407758740099:ios:25392d6da5302b850319b6',
    messagingSenderId: '407758740099',
    projectId: 'focusbuddy-6a5cf',
    storageBucket: 'focusbuddy-6a5cf.firebasestorage.app',
    iosBundleId: 'com.example.focusBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALJ2K-lTiPxDtqYwHvBJAoKHLIeG6oPvk',
    appId: '1:407758740099:ios:25392d6da5302b850319b6',
    messagingSenderId: '407758740099',
    projectId: 'focusbuddy-6a5cf',
    storageBucket: 'focusbuddy-6a5cf.firebasestorage.app',
    iosBundleId: 'com.example.focusBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARKu9hmeFcvVoHFYYsCdVOjwLpNEUAoh0',
    appId: '1:407758740099:web:94d685943deb835a0319b6',
    messagingSenderId: '407758740099',
    projectId: 'focusbuddy-6a5cf',
    authDomain: 'focusbuddy-6a5cf.firebaseapp.com',
    storageBucket: 'focusbuddy-6a5cf.firebasestorage.app',
    measurementId: 'G-TZ8612HPZQ',
  );
}
