// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:nuradar/features/tasks/data/models/task_model.dart';
import 'package:nuradar/features/tasks/domain/entities/task_priority.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MilestoneModelAdapter());
    registerAdapter(TaskModelAdapter());
    registerAdapter(TaskPriorityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MilestoneModelAdapter());
    registerAdapter(TaskModelAdapter());
    registerAdapter(TaskPriorityAdapter());
  }
}
